//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-images-SSD_SERVICE_ID_sd_BjJGPAtMLKKqJc5y
import { images as SSD_SERVICE_ID_sd_BjJGPAtMLKKqJc5y } from './sd-services/images';

export const UserRoutes = [
    //CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-images-SSD_SERVICE_ID_sd_BjJGPAtMLKKqJc5y
SSD_SERVICE_ID_sd_BjJGPAtMLKKqJc5y,
];
